spring.datasource.url=jdbc:mysql://localhost:3306/hmsapp
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.algorithm.key=${JWT_SECRET_KEY}
jwt.issuer=${JWT_ISSUER}
jwt.expiry.duration=${JWT_EXPIRY}

# S3
accessKey=${AWS_ACCESS_KEY}
secretKey=${AWS_SECRET_KEY}
region=${AWS_REGION}
cloud.aws.region.static=${AWS_REGION}

# Twilio
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE}

# Email
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
