spring.application.name=hmsapp

#JDBC Details
spring.datasource.url=jdbc:mysql://localhost:3306/hmsapp
spring.datasource.username=root
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update

jwt.algorithm.key=haksjdvhflkasdjh-audfhlaskjdfhblasdk-alksudhvlkudhvyhtfbluyt
jwt.issuer=thousif
jwt.expiry.duration=86400000

#S3
accessKey=AKIAQR5EPN6VZGSOT4B3
secretKey=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
region=eu-north-1
cloud.aws.region.static=eu-north-1
cloud.aws.region.auto=false
cloud.aws.stack.auto=false
spring.main.allow-bean-definition-overriding=true
logging.level.com.amazonaws.util.EC2MetadataUtils=error
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher=error

twilio.account.sid=ACcdaa325a491b9e907f175fbba472fb4f
twilio.auth.token=553dffa2c1d41be5b53d072cf41d2d79
twilio.phone.number=+17177347530

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smnhussainy786@gmail.com
spring.mail.password=tsgx epir zuxa ssol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
